### ISSUE TITLE
Story Outline (5/31)

### ISSUE THREAD

**Issue by aflies1** [promazo/content#39]
Create notes on the video. Create a story outline for the blog piece. Pitch story to the editor and secure approval before writing the first draft.

**Comment by Zen-8** [comment]
Video Notes
-Never got a job he didn’t start himself, first one being Paypal
-The last job was Hustle during college to put himself through school (Civilian contractor for U.S. Army Corp. of Engineers)
-Wrote air traffic control software for the army just a few miles off-campus
-Getting into entrepreneurship was random and was more in pursuit of paying for school
-Sophmore spent much time in computer working on projects and codes himself
-Took the opportunity to start a business with his other two friends
-Had a plan to graduate, teach, but instead was sparked by conversations and ideas by his peers on campus
-First company failed
-Learned the value of taking risks
-By the time he graduated, already failed with 3 companies
-When he tried to recruit for Paypal, those interning and working became comfortable with their jobs, salary, etc 
-“I’ll get to it”
-“If you have no idea what to do, join a startup, but find one where you have the passion for what they’re doing, [their] real connection with the mission and learn on someone else’s time basically watch what it takes to succeed or possibly fail at a startup without having to sort of knowing everything upfront.”
-Start now rather than later
-The level of risk-taking is on a company than an individual
-Don’t be afraid to step in or take ownership
-Force yourself through barriers because the cause/goal is where it’s at
   Affirm
-started from a vision from Paypal: Paypal goal: to make credit cards more successful online
-So Affirm is alt. To credit cards to allow more transparency/honesty due to millennials not having that trust within credit cards (allows you to pay for things over time through interest installments & never charge any extra fee)
-Know your morals, core values, and take pride in the decisions you make
-Transparency


Story Pitches
-Learning to take risks during and out of college
-Tips for motivation on landing on your own after college
-Steps to help you prepare for life beyond college
-Ways to increase your outlook before and after graduation

Story Outline
-An intro to what a typical college lifestyle look like that means classes, job(s), expenses, etc and introducing Max Levchin 
-Ending intro with what happens as you come to close in your college year
-Providing several tips/ paragraphs about your options like what it means taking risks, joining a startup, creating your own business/startup, resources that might be provided for you on campus before you graduate, etc
-Some steps/ advice Max Levchin has
-Concluding with a reminder about the steps you can take, how to stay motivated and positive throughout this, and what the overall goal is
